# Авторизация-----------------------------------------------------------------------
# Токен выдается при создании пользователя. 
# По запросу с "operation": "authorize" можно получить новый токен, указав верный пароль
# Если пользователь забыл пароль, по запросу "operation": "reset" ему на почту высылается 
# новый токен. По запросу "operation": "activate" с новым токеном можно установить новый пароль

POST http://localhost:8000/authorization/
Content-Type: application/json

{
    "operation": "authorize",
    "username": "test_user",
    "password": "12345"      
}
###
POST http://localhost:8000/authorization/
Content-Type: application/json
Authorization: Token b30bc95bebc6aa48be8f719a83a0cc8a

{
    "operation": "reset",
    "username": "test_user"    
}
###

POST http://localhost:8000/authorization/
Content-Type: application/json
Authorization: Token e0863cf688d99daa758d4ebda1dd8390

{
    "operation": "activate",
    "username": "test_user",
    "password": "password"
}
###
