# Корзина заказов-------------------------------------------------------------
# Если указан токен админа, выводятся все заказы. Если пользователя, 
# то только заказ этого пользователя.

GET http://localhost:8000/cart
Authorization: Token 123

###
# Токен пользователя: 0dfc217cf96b1a22d637f6b6531ffad2
GET http://localhost:8000/cart
Authorization: Token 0dfc217cf96b1a22d637f6b6531ffad2

###
# Токен заказчика: 8df2190d59927eb88856b87ecb75f03c
GET http://localhost:8000/cart
Authorization: Token 8df2190d59927eb88856b87ecb75f03c

###

# Добавление товара в корзину
POST http://localhost:8000/cart/
Authorization: Token ab47840f79aff811e0c6d10842933165
Content-Type: application/json

{
    "product": 3,
    "store": 1,
    "quantity": 10
}

###

# Удаление товара из корзины
DELETE  http://localhost:8000/cart/
Authorization: Token 8df2190d59927eb88856b87ecb75f03c
Content-Type: application/json

{   
    "id": 2,
    "position": 19,
    "quantity": 1
}