# Корзина заказов-------------------------------------------------------------
# Если указан токен админа, выводятся все заказы. Если пользователя, 
# то только заказ этого пользователя.

GET http://localhost:8000/cart
Authorization: Token ...

###
GET http://localhost:8000/cart
Authorization: Token ...

###

# Добавление товара в корзину
POST http://localhost:8000/cart/
Authorization: Token ...
Content-Type: application/json

{
    "product": 3,
    "store": 1,
    "quantity": 10
}

###

# Удаление товара из корзины
DELETE  http://localhost:8000/cart/
Authorization: Token ...
Content-Type: application/json

{   
    "id": 2,
    "position": 19,
    "quantity": 1
}