# Категории-----------------------------------------------------------------------
# Добавлять, удалять и переименовывать категории может только пользователь с ролью admin

GET http://localhost:8000/categories/
###
POST http://localhost:8000/categories/
Content-Type: application/json
Authorization: Token 123

{
    "name": "Кошки"
}
###
DELETE http://localhost:8000/categories/
Content-Type: application/json
Authorization: Token 123

{
    "name": "Кошки"
}
###
PATCH http://localhost:8000/categories/
Content-Type: application/json
Authorization: Token 123

{
    "id": 2,
    "name": "Мыши"
}
