# Импорт данных--------------------------------------------------------------
# Импортировать может только admin
# Токен администратора: 123

POST http://localhost:8000/import/
Content-Type: application/json
Authorization: Token 123

{
    "file": "data.yaml"
}