# Просмотр, исполнение, отмена заказов-------------------------------------------
# Наличие заказов в системе видит только админ, 
# Отменять заказ может заказчик или админ
# Отправить заказ в работу может только покупатель

GET http://localhost:8000/orders/?user=buyer_1&status=completed
Authorization: Token ...

###
GET http://localhost:8000/orders/
Authorization: Token ...

###
# Метод post используется для отправки заказа в работу
POST http://localhost:8000/orders/
Authorization: Token ...
Content-Type: application/json

{
    "id": 2
}

###

# Метод patch используется для отмены заказа, заказу проставляется статус canceled.
# Право только у админа и хозяина заказа

PATCH http://localhost:8000/orders/
Authorization: Token ...
Content-Type: application/json

{
    "id": 1
}
###

DELETE http://localhost:8000/orders/
# Метод delete используется для полного удаления заказа невзирая на статус.
# Право только у админа и хозяина заказа
Authorization: Token ...
Content-Type: application/json

{
    "id": 1
}
