# Параметры-----------------------------------------------------------------------
# Удалять и переименовывать параметры может только пользователь с ролью admin
# Добавлять параметры может также пользователь с ролью seller

GET http://localhost:8000/parameters/
###
POST http://localhost:8000/parameters/
Content-Type: application/json
Authorization: Token ...

{
    "name": "CPU"
}
###
DELETE http://localhost:8000/parameters/
Content-Type: application/json
Authorization: Token ...

{
    "id": 8
}
###
PATCH http://localhost:8000/parameters/
Content-Type: application/json
Authorization: Token ...

{
    "id": 8,
    "name": "CPU"
}