# Товары-----------------------------------------------------------------------
# Удалять и изменять товары может только admin
# Добавлять товар может админ или продавец

GET http://localhost:8000/products/
###

POST http://localhost:8000/products/
Content-Type: application/json
Authorization: Token 123

{
    "name": "Logitech mouse",
    "category": 2,
    "description": "New mouse"

}
###
DELETE http://localhost:8000/products/
Content-Type: application/json
Authorization: Token 123

{
    "id": 3
}
###
PATCH http://localhost:8000/products/
Content-Type: application/json
Authorization: Token 123

{
    "id": 2,
    "name": "Logitech new mouse",
    "category": 2,
    "description": "New test product"
}
