# Товары-----------------------------------------------------------------------
# Удалять и изменять товары может только admin
# Добавлять товар может админ или продавец

GET http://localhost:8000/products/
###

POST http://localhost:8000/products/
Content-Type: application/json
Authorization: Token ...

{
    "name": "Test product",
    "category": 3,
    "description": "New test product"

}
###
DELETE http://localhost:8000/products/
Content-Type: application/json
Authorization: Token ...

{
    "id": 8
}
###
PATCH http://localhost:8000/products/
Content-Type: application/json
Authorization: Token ...

{
    "id": 8,
    "name": "Test product_2",
    "category": 3,
    "description": "New test product"
}
