# Товары в магазине--------------------------------------------------------------
# Удалять и изменять наличие товара в магазине может только admin или хозяин магазина
# Токен обычного пользователя: a4d0d70644badae2dae57a737e852c84
# Токен администратора: c69b72525a6d23bda089af712dd5677c
# Токен хозяина тестового магазина: 0dfc217cf96b1a22d637f6b6531ffad2 
# Токен другого продавца: 0f389d5ceeb069ab472c7f63886788ed

GET http://localhost:8000/product_in_store/

###
GET http://localhost:8000/product_in_store/?store=Связной&product=IPhone 14

###
POST http://localhost:8000/product_in_store/
Content-Type: application/json
Authorization: Token 0dfc217cf96b1a22d637f6b6531ffad2

{
    "product": 9,
    "store": 8,
    "quantity": 5,
    "price": 200

}
###
DELETE http://localhost:8000/product_in_store/
Content-Type: application/json
Authorization: Token 0dfc217cf96b1a22d637f6b6531ffad2

# Установить delete_product: yes, если необходимо полностью удалить позицию
{
    "product": 9,
    "store": 8,
    "quantity": 50,
    "delete_product": "yes"
}
###
PATCH http://localhost:8000/product_in_store/
Content-Type: application/json
Authorization: Token c69b72525a6d23bda089af712dd5677c

{
    "product": 9,
    "store": 8,
    "quantity": 15,
    "price": 200
}