# Магазины-----------------------------------------------------------------------
# Удалять, создавать и переименовывать магазины может только пользователь с ролью admin
# Хозяин магазина должен иметь роль seller 


GET http://localhost:8000/stores/
###
POST http://localhost:8000/stores/
Content-Type: application/json
Authorization: Token 123

{    
    "name": "New Shop_3",
    "owner": 3,
    "delivery_cost": 100,
    "active": 1
}
###
DELETE http://localhost:8000/stores/
Content-Type: application/json
Authorization: Token 123

{
    "id": 3
}
###
PATCH http://localhost:8000/stores/
Content-Type: application/json
Authorization: Token 123

{
    "id": 1,
    "name": "Связной",
    "owner": 3,
    "delivery_cost": 200,
    "active": 1

}