# Пользователи-----------------------------------------------------------------------
# Удалять, создавать и изменять пользователей может только admin


GET http://localhost:8000/users/
###

POST http://localhost:8000/users/
Content-Type: application/json
Authorization: Token ...

{    
    "name": "test_user",
    "password": "12345",
    "role": "buyer",
    "email": "test_buyer@test.com",
    "address_1": "address_1_test_buyer"
}
###
DELETE http://localhost:8000/users/
Content-Type: application/json
Authorization: Token ...

{
    "name": "test_user"
}
###
PATCH http://localhost:8000/users/
Content-Type: application/json
Authorization: Token ...

{
    "id": 8,
    "name": "Test seller_2",
    "password": "12345",
    "role": "seller",
    "email": "test2_seller@test.com",
    "address_1": "address_1_test_seler_2"
}