# Пользователи-----------------------------------------------------------------------
# Удалять, создавать и изменять пользователей может только admin


GET http://localhost:8000/users/
###

POST http://localhost:8000/users/
Content-Type: application/json
Authorization: Token 123

{    
    "name": "test_user2",
    "password": "12345",
    "role": "buyer",
    "email": "sbitneыыыv@yandex.ru",
    "address_1": "address_1_test_buyer"
}
###
DELETE http://localhost:8000/users/
Content-Type: application/json
Authorization: Token 123

{
    "name": "test_user2"
}
###
PATCH http://localhost:8000/users/
Content-Type: application/json
Authorization: Token 123

{
    "name": "test_user2",
    "password": "12345",
    "role": "seller",
    "email": "test2_seller@test.com",
    "address_1": "address_1_test_seler_2"
}