# Generated by Django 4.2.1 on 2023-10-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_description_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
        migrations.RemoveField(
            model_name='position',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='store_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productstore',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productstore',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderPosition',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders', through='backend.OrderProduct', to='backend.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(related_name='products', through='backend.OrderProduct', to='backend.order'),
        ),
    ]
