# Generated by Django 4.2.1 on 2023-10-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='positions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.orderedpositions'),
        ),
    ]
