# Generated by Django 4.2.1 on 2023-10-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
