# Generated by Django 4.2.1 on 2023-10-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(null=True, related_name='products', through='backend.OrderProduct', to='backend.order'),
        ),
    ]
