# Generated by Django 4.2.1 on 2023-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
