# Generated by Django 4.2.1 on 2023-10-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(related_name='products', through='backend.OrderProduct', to='backend.order'),
        ),
    ]
